---
- name: Start Traffic Capture on CTO node
  hosts: cto
  become: yes
  tasks:
    - name: Install tcpdump
      apt:
        name: tcpdump
        state: present
        update_cache: yes

    - name: Start tcpdump in the background
      shell: "nohup tcpdump -i any -w /tmp/cto_traffic.pcap > /dev/null 2>&1 & echo $! > /tmp/tcpdump.pid"
      args:
        creates: /tmp/tcpdump.pid # Prevents starting if pid file already exists
